In [12]:
import numpy as np
import math

input_X = np.asarray([
    [2, 2, 2, 2, 2, 1, 1, 1],
    [2, 2, 2, 2, 2, 1, 1, 1],
    [2, 2, 2, 2, 2, 1, 1, 1],
    [2, 2, 2, 2, 2, 1, 1, 1],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    ], dtype=np.float32)

print('Images:', input_X.shape)
print(input_X)

filters = np.asarray([
    [-1, 0, 1], 
    [-1, 0, 1], 
    [-1, 0, 1]
    ])

print('Filters:', filters.shape)

bias = 0.5

stride = 2

h, w = input_X.shape
filter_h, filter_w = filters.shape

padding = 1
temp_X = np.zeros((h+2*padding,w+2*padding), dtype=np.float32)
temp_X[padding:-padding,padding:-padding] = input_X
padding_X = temp_X
print('padding_X')
print(padding_X)

h, w = padding_X.shape

filter_h_offset = int(math.floor(filter_h/2)) # 1 = floor(3/2)
filter_w_offset = int(math.floor(filter_w/2)) # 1 = floor(3/2)

# print(filter_h_offset, filter_w_offset)

# output_X = np.zeros((h - 2 * filter_h_offset, w - 2 * filter_w_offset))
output_X = np.zeros_like(padding_X, dtype=np.float32)
print("output_X")
print(output_X)

Images: (8, 8)
[[2. 2. 2. 2. 2. 1. 1. 1.]
 [2. 2. 2. 2. 2. 1. 1. 1.]
 [2. 2. 2. 2. 2. 1. 1. 1.]
 [2. 2. 2. 2. 2. 1. 1. 1.]
 [2. 2. 2. 9. 9. 9. 9. 9.]
 [2. 2. 2. 9. 9. 9. 9. 9.]
 [2. 2. 2. 9. 9. 9. 9. 9.]
 [2. 2. 2. 9. 9. 9. 9. 9.]]
Filters: (3, 3)
padding_X
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 2. 2. 2. 2. 1. 1. 1. 0.]
 [0. 2. 2. 2. 2. 2. 1. 1. 1. 0.]
 [0. 2. 2. 2. 2. 2. 1. 1. 1. 0.]
 [0. 2. 2. 2. 2. 2. 1. 1. 1. 0.]
 [0. 2. 2. 2. 9. 9. 9. 9. 9. 0.]
 [0. 2. 2. 2. 9. 9. 9. 9. 9. 0.]
 [0. 2. 2. 2. 9. 9. 9. 9. 9. 0.]
 [0. 2. 2. 2. 9. 9. 9. 9. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
output_X
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
for i in range(filter_h_offset, h - filter_h_offset, stride):
    for j in range(filter_w_offset, w - filter_w_offset, stride):
        element_wise_produt = padding_X[i-filter_h_offset:i+filter_h_offset + 1, j-filter_w_offset:j+filter_w_offset + 1] * filters
        # print(sum(sum(element_wise_produt)))
        output_X[i, j] = sum(sum(element_wise_produt)) + bias
# output_X = output_X[filter_h_offset:h-filter_h_offset, filter_w_offset:w-filter_w_offset]
print(output_X.shape)
print(output_X)

(10, 10)
[[ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   4.5  0.   0.5  0.  -1.5  0.   0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   6.5  0.   0.5  0.  -2.5  0.   0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   6.5  0.  14.5  0.  -0.5  0.   0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   6.5  0.  21.5  0.   0.5  0.   0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0. ]]


In [15]:
output_X = output_X[filter_h_offset:h-filter_h_offset, filter_w_offset:w-filter_w_offset]
print(output_X.shape)
print(output_X)


(7, 7)
[[ 0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.5  0.  -2.5  0.   0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0. ]
 [ 0.  14.5  0.  -0.5  0.   0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0. ]
 [ 0.  21.5  0.   0.5  0.   0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   0. ]]
