In [1]:
import numpy as np

input_X = np.asarray([
    [2, 2, 2, 2, 2, 1, 1, 1],
    [2, 2, 2, 2, 2, 1, 1, 1],
    [2, 2, 2, 2, 2, 1, 1, 1],
    [2, 2, 2, 2, 2, 1, 1, 1],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    ], dtype=np.float32)

kernel = np.asarray([
    [-1, 0, 1], 
    [-1, 0, 1], 
    [-1, 0, 1]
    ])

bias = 0.5
stride = 2
padding = 1

In [2]:
print('input_X:', input_X.shape)
print(input_X)

print('kernel:', kernel.shape)
print(kernel)

input_X: (8, 8)
[[2. 2. 2. 2. 2. 1. 1. 1.]
 [2. 2. 2. 2. 2. 1. 1. 1.]
 [2. 2. 2. 2. 2. 1. 1. 1.]
 [2. 2. 2. 2. 2. 1. 1. 1.]
 [2. 2. 2. 9. 9. 9. 9. 9.]
 [2. 2. 2. 9. 9. 9. 9. 9.]
 [2. 2. 2. 9. 9. 9. 9. 9.]
 [2. 2. 2. 9. 9. 9. 9. 9.]]
kernel: (3, 3)
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]


In [3]:
padding_X = np.pad(input_X, ((padding, padding), (padding, padding)),
                   'constant', constant_values=0)

print("padding_X.shape: ", padding_X.shape)
padding_X

padding_X.shape:  (10, 10)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 2., 2., 2., 2., 1., 1., 1., 0.],
       [0., 2., 2., 2., 2., 2., 1., 1., 1., 0.],
       [0., 2., 2., 2., 2., 2., 1., 1., 1., 0.],
       [0., 2., 2., 2., 2., 2., 1., 1., 1., 0.],
       [0., 2., 2., 2., 9., 9., 9., 9., 9., 0.],
       [0., 2., 2., 2., 9., 9., 9., 9., 9., 0.],
       [0., 2., 2., 2., 9., 9., 9., 9., 9., 0.],
       [0., 2., 2., 2., 9., 9., 9., 9., 9., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [4]:
kernel_height, kernel_width = kernel.shape
input_height, input_width = input_X.shape

output_height = (input_height - kernel_height + 2 * padding) // stride + 1
output_width = (input_width - kernel_width + 2 * padding) // stride + 1

output_X = np.zeros((output_height, output_width))

for y in range(output_height):
    for x in range(output_width):
        output_X[y][x] = (kernel * padding_X[y*stride : y*stride + kernel_height, x*stride : x*stride + kernel_width]).sum() + bias

print('Output:', output_X.shape)
print(output_X)

Output: (4, 4)
[[ 4.5  0.5 -1.5  0.5]
 [ 6.5  0.5 -2.5  0.5]
 [ 6.5 14.5 -0.5  0.5]
 [ 6.5 21.5  0.5  0.5]]
