#### Q1.

$A = \begin{pmatrix} 
1 && -2 && 3 && 5 \\
2 && 2 && -1 && 0 \\
3 && 0 && 1 && 2 \\
1 && 0 && 2 && 0 \end{pmatrix}$

2A, $A^T$, $A^{-1}$, A의 계수를 구하시오.


In [1]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import matrix_rank
from numpy.linalg import det
from numpy.linalg import eig
from numpy.linalg import svd

a = [[1, -2, 3, 5],
    [2, 2, -1, 0],
    [3, 0, 1, 2],
    [1, 0, 2, 0]]

A = np.array(a)

In [7]:
print("=============== A matrix ==============")
print(A)
print("==========================================")
print("=============== 2A matrix ================")
print(2*A)
print("==========================================")
print("=============== A^T matrix ===============")
print(A.T)
print("==========================================")
print("=============== A^-1 matrix ==============")
print(inv(A))
print("==========================================")
print("==========================================")
print("A rank(계수)", matrix_rank(A))

=============== A matrix ==============
[[ 1 -2  3  5]
 [ 2  2 -1  0]
 [ 3  0  1  2]
 [ 1  0  2  0]]
=============== 2A matrix ================
[[ 2 -4  6 10]
 [ 4  4 -2  0]
 [ 6  0  2  4]
 [ 2  0  4  0]]
=============== A^T matrix ===============
[[ 1  2  3  1]
 [-2  2  0  0]
 [ 3 -1  1  2]
 [ 5  0  2  0]]
=============== A^-1 matrix ==============
[[-0.23529412 -0.23529412  0.58823529 -0.05882353]
 [ 0.29411765  0.79411765 -0.73529412  0.32352941]
 [ 0.11764706  0.11764706 -0.29411765  0.52941176]
 [ 0.29411765  0.29411765 -0.23529412 -0.17647059]]
A rank(계수) 4


In [3]:
print("=============== det(A)(행렬식) ===============")
print(det(A))

=============== det(A)(행렬식) ===============
34.00000000000001


In [4]:
print("=============== A eigen decomposition(고유값 분해) ===============")
w, v = eig(A)

print("w.shape: {}, v.shape: {}".format(w.shape, v.shape))
print("w(eigenvalues): \n{}".format(w))
print("v(The normalized  eigenvetors): \n{}".format(v))
print("the column v[:,i] is the eigenvector corresponding to the eigenvalue w[i].")

=============== A eigen decomposition(고유값 분해) ===============
w.shape: (4,), v.shape: (4, 4)
w(eigenvalues): 
[ 5.52552524+0.j         -1.52204833+1.31733645j -1.52204833-1.31733645j
  1.51857142+0.j        ]
v(The normalized  eigenvetors): 
[[-0.68465996+0.j          0.619935  +0.j          0.619935  -0.j
   0.11199539+0.j        ]
 [-0.21666012+0.j         -0.34875983-0.24694874j -0.34875983+0.24694874j
  -0.93998928+0.j        ]
 [-0.60547918+0.j         -0.31379356-0.41033136j -0.31379356+0.41033136j
  -0.22854692+0.j        ]
 [-0.34306572+0.j         -0.263929  +0.31075191j -0.263929  -0.31075191j
  -0.22725204+0.j        ]]
the column v[:,i] is the eigenvector corresponding to the eigenvalue w[i].


In [5]:
print("=============== A svd(singular value decomposition(특이값 분해) ===============")
U, s , Vh = svd(A)
print("U.shape: {}\nV.shape: {}\ns.shape: {}".format(U.shape, Vh.shape, s.shape))
print("U matrix: \n{}".format(U))
print("diagonal matrix: \n{}".format(s))
print("V matrix: \n{}".format(Vh))

=============== A svd(singular value decomposition(특이값 분해) ===============
U.shape: (4, 4)
V.shape: (4, 4)
s.shape: (4,)
U matrix: 
[[-0.8819521   0.25706354 -0.24178316 -0.31244156]
 [ 0.05743106 -0.76320224 -0.26028922 -0.58862003]
 [-0.42722253 -0.58124436  0.04756433  0.69092224]
 [-0.19063859 -0.11660051  0.93355667 -0.28023773]]
diagonal matrix: 
[6.97059301 3.8068416  1.85521105 0.69063894]
V matrix: 
[[-0.32126336  0.26952747 -0.50380033 -0.75520197]
 [-0.8221184  -0.53601693  0.18911937  0.03226532]
 [ 0.16919264 -0.01995035  0.78137601 -0.60035603]
 [ 0.43850318 -0.7997767  -0.31602313 -0.2611543 ]]


#### Q2.

$A = \begin{pmatrix}
1 && -2 \\
2 && 2 \end{pmatrix}$

$A^{1/2}$, $A^{-1/2}$를 구하시오.

In [ ]:
import numpy as np
import numpy.linalg as lin
from scipy import linalg

# scipy의 linalg.sqrtm(행렬)을 사용하여 제곱근 행렬을 계산한다.
pro_A = np.array([[1, -2], [2, 2]])
AOneOverTwo = linalg.sqrtm(pro_A)
print(f"A^1/2 = \n{AOneOverTwo}")
print("++++++++++++++++++++++++++++++++++++")
print(np.sqrt(pro_A))
# print(f"A^-1/2 = \n{lin.inv(AOneOverTwo)}")

#### Q4.

$f_1(x) = -2x_1x_1 -1.5x_1x_2+3.1x_1x_4+2x_2x_1+2x_2x_x-6x_2x_4-2.1x_3x_1+3x_3x_3+2x_4x_1+3x_4x_2-2x_4x_4+1.2x_1+3.3x_2-4x_4+4.2$

$f_2(x) = 3x_1x_1+3.5x_1x_3-3.1x_1x_4+2.1x_2x_1-2x_2x_2-2x_2x_4-2.5x_3x_1+3x_3x_3+3x_4x_1-6x_4x_2+2x_4x_3+2.2x_1+2.3x_2+3.3x_3-2x_4+5.1$

In [1]:
import numpy as np
func1_A = np.array([[-2, -1.5, 0, 3.1], 
                    [2, 2, 0, -6], 
                    [-2.1, 0, 3, 0], 
                    [2, 3, 0, -2]])
func1_bT = np.array([1.2, 3.3, 0, -4])
func1_c = 4.2

func2_A = np.array([[3, 0, 3.5, -3.1], 
                    [2.1, -2, 0, -2], 
                    [-2.5, 0, 3, 0], 
                    [3, -6, 2, 0]])
func2_bT = np.array([2.2, 2.3, 3.3, -2])
func2_c = 5.1

func_A_Sum = func1_A + func2_A
func_bT_Sum = func1_bT + func2_bT
func_c_Sum = func1_c + func2_c

print("func_A")
print(func_A_Sum)

print("func_bT")
print(func_bT_Sum)

print("func_c")
print(func_c_Sum)


func_A
[[ 1.  -1.5  3.5  0. ]
 [ 4.1  0.   0.  -8. ]
 [-4.6  0.   6.   0. ]
 [ 5.  -3.   2.  -2. ]]
func_bT
[ 3.4  5.6  3.3 -6. ]
func_c
9.3


#### Q5.

놈을 계산하시오.  
(1) $x = (3, -4, -1.2, 0 2.3)^T$

(2)$\begin{pmatrix}
2 && 1 \\
1 && 5 \\
4 && 1 \end{pmatrix}$ 의 Frobenius norm

In [2]:
import numpy as np
from numpy.linalg import norm

mat_x = np.array([3, -4, -1.2, 0, 2.3])

mat_x_transposed = mat_x.T

print("============== 1-norm =============")
print(norm(mat_x_transposed, ord=1))
print("============== 2-norm =============")
print(norm(mat_x_transposed, ord=2))
print("============== 3-norm =============")
print(norm(mat_x_transposed, ord=3))
print("============= Max-norm ============")
print(norm(mat_x_transposed, ord=np.inf))

import numpy as np
from numpy.linalg import norm

mat_x =np.array([[2, 1],
                 [1, 5],
                 [4, 1]])

print("============== Frobenius norm =============")
print(norm(mat_x, ord='fro'))

============== 1-norm =============
10.5
============== 2-norm =============
5.632938842203065
============== 3-norm =============
4.716120891176797
============= Max-norm ============
4.0
============== Frobenius norm =============
6.928203230275509


#### Q6.
##### [예제 2-3]에서 임계값 T가 T = 2.0으로 바뀌었다고 가정하고 [그림 2-4(b)]를 새로 그리시오. T가 변함에 따라 어떤 변화가 나타나는지 설명하시오.


In [2]:
import numpy as np
from numpy.linalg import norm
import plotly.graph_objects as go
from plotly.subplots import make_subplots


row = [1, 2, 1, 2]
col = [1, 1, 2, 2]
color = ['orRd', 'YlGn', 'twilight']

# normal vector
# arbitary point
w = np.array([1.2, 0.7, 1.0]) # direction x2
T = 2.0

d = []
z = []

d.append(np.absolute(0.584*norm(w, ord=2)))
d.append(2.0/norm(w, ord=2))
d.append(3.0/norm(w, ord=2))

# Create x, y
x, y = np.meshgrid(range(2), range(2))

for i in range(3):
    print("frist distance from orignal point:", d[i])
    # Caculate corresponding z
    z.append((-w[0] * x - w[1] * y - d[i]) * 1. /w[2])


# plot the surface
fig = make_subplots(
    rows=2, cols=2,
    specs=[[{'type': 'surface'}, {'type': 'surface'}],
           [{'type': 'surface'}, {'type': 'surface'}]])

fig.update_layout(
    title_text='3D subplots with different colorscales',
    height=800,
    width=800
)

for i in range(3):
    fig.add_trace(
        go.Surface(x=x, y=y, z=z[i], colorscale=color[i], showscale=False),
        row=row[i], col=col[i])
    fig.add_trace(
        go.Scatter3d(x=[0], y=[0], z=[0], mode='markers'),
        row=row[i], col=col[i])
    
    fig.add_trace(
        go.Surface(x=x, y=y, z=z[i], colorscale=color[i], showscale=False),
        row=2, col=2)

fig.add_trace(
    go.Scatter3d(x=[0], y=[0], z=[0], mode='markers'),
    row=2, col=2)

fig.show()

frist distance from orignal point: 0.9996469776876233
frist distance from orignal point: 1.168412475673972
frist distance from orignal point: 1.752618713510958


#### [Solution]
plane_y = $1.2x_1 + 0.7x_2 + 1.0x_3$\
$ = 2.0 = T$

$1.2x_1 + 0.7x_2 + 1.0x_3 = 2.0$ \
$1.2x_1 + 0.7x_2 + 1.0x_3 - 2.0 = 0 $

**T 가 커짐에 따라 결정 평편은 점점 원점으로 부터 멀어지기 때문에 평면은 아래로 내려가는 모양일 것이고, 임계값이 증가하면 증가할 수록 평면의 y절편은 증가할 것이다.**

**그림에서는 원점으로 부터 아래의 수식 만큼 떨어져 있기 때문에 원점으로 부터 T 가 증가하면 평면은 멀어지고 작아지면 가까워 진다.**
$T/||W|_2$

#### Q7.
##### 아래 그림은 x1과 x3 축이 이루는 평면이 결정평면인 상황이다. 이에 해당하는 퍼셉트론을 [그림 2-4(a)]처럼 제시하시오.

In [70]:
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

x, z = np.meshgrid(range(2), range(2))
y = x*0

print("======== perceptron of plain above ================")
print("          0")
print("x1 ---O-----\\")
print("          1  \\")
print("x2 ---O--------O---- output")
print("          0  / T=1.0")
print("x3 ---O-----/")


# plot the surface
fig = go.Figure()

# original point
fig.add_trace(go.Scatter3d(x=[0], y=[0], z=[0], mode='markers'))
fig.add_trace(go.Surface(x=x, y=y, z=z, showscale=False, opacity=0.6))

fig.show()

======== perceptron of plain above ================
          0
x1 ---O-----\
          1  \
x2 ---O--------O---- output
          0  / T=1.0
x3 ---O-----/


##### [Solution]
######
그림에서는 x1과 x3 축이 이루는 평면을 나타내고 있음. 평면의 방정식을 유도하기 위해서 다음과 같은 사항을 알아야함.

1. 그 평면을 지나는 점 P0(x0, y0, z0)를 적어도 하나 알아야 한다.

> 이 평면을 지나는 점을 (0, 0, 0)이라 하자.

2. 그 평면에 수직인 법선벡터를 알아야 한다.

이 그림에서의 평면에 수직인 벡터는
> $(x_1, x_2, x_3) = (0, k, 0)$ 이고, 벡터 연산으로 표현하면,\
> $t(W^Tx)=t((0 \ 1 \ 0)^T (x_1, x_2, x_3))$
> t는 비선형 함수

따라서 다음 정리하면
> 한 점 $(x_0, y_0, z_0)$을 지나고, \
> 법선 벡터가 $n = <a, b, c>$인 \
> 평면의 방정식은 $a(x-x_0) + b(y - y_0) + c(z - z_0) = 0$ 이다.

구하고자 하는 평면의 방정식은 $kx_2 = 0$이다. 
따라서 여기서 나오는 퍼셉트론의 가중치 값은 오로지 x_2의 k값으로만 결정되고, 임계값은 0일 것이다.